sudo: required
dist: trusty
# Force travis to use its minimal image with default Python settings
language: generic
compiler:
  - gcc

env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
    - CATKIN_WS_UNDERLAY=~/catkin_ws_underlay
    - CATKIN_WS_UNDERLAY_SRC=${CATKIN_WS_UNDERLAY}/src
    - CI_ROS_DISTRO="indigo"
    - DEFAULT_ROSINSTALL="https://raw.githubusercontent.com/ipa320/care-o-bot/${CI_ROS_DISTRO}_dev/.travis.rosinstall"

install:
  - mkdir -p $CATKIN_WS_UNDERLAY_SRC
  - git clone https://github.com/ipa320/cob_robots.git /tmp/cob_robots
  - mv /tmp/cob_robots/cob_supported_robots  $CATKIN_WS_UNDERLAY_SRC/
  - rm -rf /tmp/cob_robots
  - wget https://raw.githubusercontent.com/ipa320/care-o-bot/${CI_ROS_DISTRO}_dev/.travis.install.sh
  - bash .travis.install.sh

script:
  - wget https://raw.githubusercontent.com/ipa320/care-o-bot/${CI_ROS_DISTRO}_dev/.travis.script.sh
  - bash .travis.script.sh
  - set -e; for x in $(find . -name '*.xacro'); do $CATKIN_WS_UNDERLAY/env.sh rosrun xacro xacro "$x" > /dev/null; done

